---
name: geoinspector

on:
 push:
   paths:
   - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    # TODO: `go vet` && `go fmt`

    - name: Build GeoInspector Code
      run: |
        mkdir -p ~/go/src/github.com/censoredplanet
        ln -s ~/work/geoinspector/geoinspector ~/go/src/github.com/censoredplanet/geoinspector
        cd ~/go/src/github.com/censoredplanet/geoinspector
        make

    - name: Upload binary
      uses: actions/upload-artifact@v1
      with:
        name: geoinspector
        path: geoinspector
...
